Repository redhat-developer/devconsole-operator, pull requests merged in 2019-04, with the labels that each got.

#62 Rename devops to dev in remaining files
  examples/devconsole_v1alpha1_component_cr.yaml
  examples/devconsole_v1alpha1_gitsource_cr.yaml
  pkg/apis/addtoscheme_devconsole_v1alpha1.go
Labels: approved

#63 Add list/watch for BuildConfig and DeploymentConfig
  deploy/role.yaml
  manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, ok-to-test

#33 Create Makefile target to install operator & test
  make/dev.mk
  make/test.mk
  test/e2e/Dockerfile.registry
  test/e2e/catalog_source.yaml
  test/e2e/component_operator_test.go
  test/e2e/component_test.go
  test/e2e/example_test.go
  test/e2e/subscription.yaml
Labels: approved, ok-to-test

#64 quiet flag appears to fail and causes unexpected behaviour
  make/test.mk
Labels: approved

#55 Merging pkg/devopsconsole-operator into pkg/devopsconsole
  pkg/apis/addtoscheme_devconsole_v1alpha1.go
  pkg/apis/devconsole-operator/v1alpha1/doc.go
  pkg/apis/devconsole-operator/v1alpha1/register.go
  pkg/apis/devconsole-operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devconsole-operator/v1alpha1/zz_generated.defaults.go
  pkg/apis/devconsole-operator/v1alpha1/zz_generated.openapi.go
  pkg/apis/devconsole/v1alpha1/gitsource_types.go
  pkg/apis/devconsole/v1alpha1/zz_generated.deepcopy.go
  test/e2e/custom_resource_operator_test.go
Labels: approved, ok-to-test

#67 Fix e2e local
  make/test.mk
  test/e2e/custom_resource_operator_test.go
Labels: approved, lgtm

#68 Clean up of catalog source and subscription
  make/test.mk
Labels: approved, lgtm

#71 Align the GOPATH with that of openshift CI src pipeline
  openshift-ci/Dockerfile.tools
Labels: approved

#72 Add Dockerfile which has image with binary
  openshift-ci/Dockerfile.deploy
Labels: approved

#73 Fix name of binary to be copied over in CI
  openshift-ci/Dockerfile.deploy
Labels: approved

#74 Correct log message
  test/e2e/component_test.go
Labels: approved

#78 In the build environment image, have a different gopath
  openshift-ci/Dockerfile.tools
Labels: approved

#79 use the correct namespace depending on target
  make/test.mk
  test/e2e/component_test.go
Labels: approved

#70 ODC-405 Remove GitSource API because it's moved to devconsole-api
  pkg/apis/devconsole/v1alpha1/gitsource_types.go
  pkg/apis/devconsole/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devconsole/v1alpha1/zz_generated.defaults.go
Labels: approved, lgtm, ok-to-test

#81 Update README.md
  README.md
Labels: approved

#83 Proper Cleanup for test-olm-integration to pass
  make/test.mk
Labels: approved

#80 Updating suitable variable names
  test/e2e/component_test.go
Labels: approved

#75 DevOps to Dev in README and csv
  README.md
  manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved

#84 Remove invalid user & duplicate entry
  OWNERS
Labels: approved

#76 after deployment add service creation
  README.md
  cmd/manager/main.go
  deploy/crds/devconsole_v1alpha1_component_crd.yaml
  deploy/role.yaml
  examples/devconsole_v1alpha1_component_cr.yaml
  make/deploy.mk
  manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml
  manifests/devconsole/0.1.0/devconsole_v1alpha1_component_crd.yaml
  pkg/apis/devconsole/v1alpha1/component_types.go
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_controller_test.go
  pkg/controller/component/component_resources.go
Labels: approved

#54 Add gitsource CR reference in component CR
  Gopkg.lock
  deploy/crds/devconsole_v1alpha1_component_crd.yaml
  deploy/crds/devconsole_v1alpha1_gitsource_crd.yaml
  examples/devconsole_v1alpha1_component_cr.yaml
  make/test.mk
  manifests/devconsole/0.1.0/devconsole_v1alpha1_component_crd.yaml
  manifests/devconsole/0.1.0/devconsole_v1alpha1_gitsource_crd.yaml
  pkg/apis/devconsole/v1alpha1/component_types.go
  pkg/apis/devconsole/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devconsole/v1alpha1/zz_generated.openapi.go
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_controller_test.go
  pkg/controller/component/component_resources.go
  test/e2e/component_test.go
Labels: approved, ok-to-test

#85 fix component controller not finding gitsource schema
  cmd/manager/main.go
  deploy/crds/devconsole_v1alpha1_component_crd.yaml
  make/deploy.mk
  manifests/devconsole/0.1.0/devconsole_v1alpha1_component_crd.yaml
  pkg/apis/devconsole/v1alpha1/zz_generated.deepcopy.go
Labels: approved

#87 Move Dockerfile.registry under the expected context
  Dockerfile.registry
  make/test.mk
  test/README.md
Labels: approved

#89 Remove the garbage entry
  make/test.mk
Labels: approved

#93 Fix typo in DEPLOYED_NAMESPACE variable
  make/test.mk
  test/e2e/component_test.go
Labels: approved

#94 enter a nodejs repo in gitsource CR to demo deployment
  examples/devconsole_v1alpha1_gitsource_cr.yaml
Labels: approved

#77 Make OLM e2e test compatible with OS4
  make/dev.mk
  make/test.mk
  test/e2e/catalog_source_OS3.yaml
  test/e2e/catalog_source_OS4.yaml
  test/e2e/component_test.go
  test/e2e/subscription_OS3.yaml
  test/e2e/subscription_OS4.yaml
Labels: approved

#96 Upgrade Operator SDK version to v0.7.0
  Gopkg.toml
Labels: approved

#90 feat(ODC-464): add GitSourceAnalysis CRD
  deploy/crds/devconsole_v1alpha1_gitsourceanalysis_crd.yaml
  examples/devconsole_v1alpha1_gitsourceanalysis_cr.yaml
  manifests/devconsole/0.1.0/devconsole_v1alpha1_gitsourceanalysis_crd.yaml
Labels: approved

#98 Add GitSourceAnalysis to devconsole manifest
  manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved

#99 Validate manifests using operator-courier
  Dockerfile
  make/find-tools.mk
  make/test.mk
  openshift-ci/Dockerfile.tools
Labels: approved

#103 added ldimaggi to reviewers
  OWNERS
Labels: approved, ok-to-test

#105 Refactor component
  Gopkg.lock
  pkg/apis/addtoscheme_components_v1alpha1.go
  pkg/apis/addtoscheme_devconsole_v1alpha1.go
  pkg/apis/devconsole/v1alpha1/component_types.go
  pkg/apis/devconsole/v1alpha1/doc.go
  pkg/apis/devconsole/v1alpha1/register.go
  pkg/apis/devconsole/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devconsole/v1alpha1/zz_generated.defaults.go
  pkg/apis/devconsole/v1alpha1/zz_generated.openapi.go
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_controller_test.go
  pkg/controller/component/component_resources.go
  test/e2e/component_test.go
Labels: approved

#104 Fix lint issues in yaml files
  deploy/crds/devconsole_v1alpha1_gitsourceanalysis_crd.yaml
  examples/devconsole_v1alpha1_component_cr.yaml
  test/e2e/subscription_OS3.yaml
  test/e2e/subscription_OS4.yaml
Labels: approved

#107 Set `GOCACHE` environment variable explicitly
  make/lint.mk
Labels: approved

#108 Use tagged version of Operator SDK
  Dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, size/XS

#109 Add an introduction about the project
  README.md
Labels: approved, size/M

#111 Remove operator-courier from test target
  make/test.mk
Labels: approved, size/XS

#110 Use `KUBECONFIG` instead of username & password
  make/dev.mk
  make/test.mk
Labels: size/XS

#112 Copy CRD files to operator and registry images
  .gitignore
  Dockerfile.dev
  Dockerfile.registry
  Makefile
  make/lint.mk
  make/test.mk
Labels: size/S

#113 Enable logs for test e2e local
  make/test.mk
Labels: approved, size/XS

#115 Make lint more predictable
  make/lint.mk
Labels: size/XS

#116 Find all YAMLs before running YAML lint
  make/lint.mk
Labels: approved, size/XS

#91 feat(ODC-466): add status properties to GitSource CRD
  deploy/crds/devconsole_v1alpha1_gitsource_crd.yaml
  examples/status/reachable_gitsource_cr.yaml
  examples/status/unreachable_gitsource_cr.yaml
  examples/status/wrong_branch_gitsource_cr.yaml
Labels: approved, size/L

#120 Fix duplicate target names
  make/test.mk
Labels: size/S

#121 Make test-e2e to run test with local operator
  make/test.mk
  test/e2e/component_test.go
Labels: size/M

#114 Adding labels and selectors
  Gopkg.lock
  pkg/controller/component/component_controller_test.go
  pkg/resource/label.go
Labels: approved, size/L

#123 Build dependencies
  make/test.mk
Labels: approved, size/XS

#124 Add status of registry build in README
  README.md
Labels: approved, size/XS

#125 Use UBI instead of centos for the deployment image
  Dockerfile
  openshift-ci/Dockerfile.deploy
Labels: approved, size/S

#119 Update version of github.com/golang/protobuf package to 1.3.1
  Gopkg.lock
  Gopkg.toml
Labels: ok-to-test, size/S

#126 remove obsolete Dockerfile
  build/Dockerfile
Labels: approved, size/XS

#127 remove cico as obsolete
  cico_build_deploy.sh
  cico_run_coverage.sh
  cico_run_tests.sh
  cico_setup.sh
Labels: approved, size/L

#128 add symbolic link build/Dockerfile -> Dockerfile.dev
  build/Dockerfile
Labels: approved, size/XS

#106 Update.status
  Gopkg.lock
  Gopkg.toml
  deploy/crds/devconsole_v1alpha1_component_crd.yaml
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_resources.go
Labels: approved, size/XL

#131 Add Travis CI configuration for e2e test
  .travis.yml
Labels: approved, size/M

#122 adding annotations
  Gopkg.lock
  pkg/controller/component/component_controller_test.go
  pkg/controller/component/component_resources.go
  pkg/resource/annotation.go
  pkg/resource/label.go
Labels: lgtm, size/M

#134 add short names for gitsource and gitsourceanalysis
  deploy/crds/devconsole_v1alpha1_gitsource_crd.yaml
  deploy/crds/devconsole_v1alpha1_gitsourceanalysis_crd.yaml
Labels: size/S

#133 Simplify.and.update.makefile
  Makefile
  README.md
  make/deploy.mk
  make/dev.mk
  pkg/controller/component/component_controller.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
Labels: approved, size/L

#132 replace general instance by component cp
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_resources.go
Labels: approved, size/L

#140 Skip resource creation with --no-setup option
  make/test.mk
Labels: approved, lgtm, size/XS

#118 feat(ODC-451): add GitSource controller that checks if repo is reachable and branch exists
  Gopkg.lock
  pkg/controller/add_gitsource.go
  pkg/controller/gitsource/gitsource_controller.go
  pkg/controller/gitsource/gitsource_controller_test.go
Labels: approved, size/L

#142 Updating devconsole api revision
  Gopkg.lock
  Gopkg.toml
Labels: approved, size/XS

#139 Update branding
  README.md
  manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, size/M

#143 Ensure temporary pull spec works in the CI
  make/test.mk
Labels: approved, size/XS

#147 Add a base image which openshift can overwrite
  Dockerfile.registry
Labels: approved, size/XS

#148 Add binaries to build registry into root image
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.tools
Labels: size/S

#149 Update env reference in registry builder
  openshift-ci/Dockerfile.registry.build
Labels: approved, size/XS

#150 Use /usr/local/bin for registry
  openshift-ci/Dockerfile.tools
Labels: size/XS

#151 Allow the INITIALIZER Abinary to be found from PATH
  openshift-ci/Dockerfile.registry.build
Labels: size/XS

#146 chore(ODC-612): remove git controllers and import them from devconsole-git repo via dependency
  Gopkg.lock
  Gopkg.toml
  pkg/controller/add_gitsource.go
  pkg/controller/add_gitsourceanalysis.go
  pkg/controller/gitsource/gitsource_controller.go
  pkg/controller/gitsource/gitsource_controller_test.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller.go
  pkg/controller/gitsourceanalysis/gitsourceanalysis_controller_test.go
Labels: approved, size/XL

#153 Move registry binaries to tmp/gopath/bin
  openshift-ci/Dockerfile.tools
Labels: size/XS

#152 chore(ODC-64): update devconsole-git to bring credentials validation
  Gopkg.lock
  Gopkg.toml
Labels: approved, size/XS

#154 Target to run e2e test with `--no-setup` option
  make/test.mk
Labels: size/S

#155 Set operator deployment namespace
  make/test.mk
Labels: size/XS

#157 Download operator-registry from a GitHub release
  openshift-ci/Dockerfile.registry.build
  openshift-ci/Dockerfile.tools
Labels: approved, size/S

#158 Expose operator registry port
  openshift-ci/Dockerfile.registry.build
Labels: approved, size/XS

#159 Apply GitSourceAnalysis CRD configuration
  make/test.mk
Labels: size/XS

#160 Set DEPLOYED_NAMESPACE to TEST_NAMESPACE
  make/test.mk
Labels: size/XS

#161 Create target to run OLM e2e test for CI
  make/test.mk
Labels: approved, size/XS

#162 Add a `-ci` suffix to indicate CI only target
  make/test.mk
Labels: size/XS

#164 Remove test namespace creation and it's usage
  make/test.mk
Labels: lgtm, size/XS

#165 Run initializer as root user
  openshift-ci/Dockerfile.registry.build
Labels: size/XS

#167 Include grpc_health_probe binary
  openshift-ci/Dockerfile.registry.build
Labels: approved, size/XS

#170 chore: update devconsole-git to add failure reasons to analysis
  Gopkg.lock
  Gopkg.toml
Labels: approved, size/XS
