Repository redhat-developer/devconsole-operator, pull requests merged in 2019-05, with the labels that each got.

#171 Increase timeout to 30 minute
  make/lint.mk
Labels: approved, size/XS

#172 Check for the existence of CRDs
  hack/check-crds.sh
  make/test.mk
Labels: size/S

#173 Increase waiting time
  hack/check-crds.sh
Labels: size/XS

#175 Use the base image available in the OpenShift CI
  openshift-ci/Dockerfile.registry.build
Labels: approved, size/S

#136 Non-admin user viewing the console with developer console perspective
  hack/install_devconsole/README.md
  hack/install_devconsole/consoledeveloper.sh
  hack/install_devconsole/create_user.sh
  hack/install_devconsole/devconsole.sh
  hack/install_devconsole/yamls/catalog_source_OS4.yaml
  hack/install_devconsole/yamls/redeploy-console-operator.yaml
  hack/install_devconsole/yamls/subscription_OS4.yaml
  hack/install_devconsole/yamls/unmanage.yaml
Labels: approved, size/L

#176 Set registry log
  openshift-ci/Dockerfile.registry.build
Labels: size/XS

#177 Make installation instruction more clear
  hack/install_devconsole/README.md
Labels: size/M

#179 Create a Dockerfile to create intermediate image
  openshift-ci/Dockerfile.registry.intermediate
Labels: size/XS

#180 Increase time to wait for pulling registry image
  hack/check-crds.sh
Labels: size/XS

#174 Create make target to push operator to the quay app registry for tests.
  Makefile
  make/test.mk
Labels: approved, ok-to-test, size/M

#182 Document continuous integration
  openshift-ci/README.md
Labels: size/L

#186 Add execute permission
  hack/check-crds-upgrade.sh
Labels: approved, size/XS

#187 Correct the steps for upgrade
  make/test.mk
Labels: size/XS

#188 Build dependencies
  make/test.mk
Labels: size/XS

#190 Create separate Makefile target to update CSV
  Makefile
Labels: size/XS

#191 Use copy & extract instead of ADD
  openshift-ci/Dockerfile.registry.build.next
Labels: size/XS

#192 Update version number
  Makefile
  test/upgrade/upgrade.py
Labels: size/S

#193 Fix typo & newline
  test/upgrade/upgrade.py
  test/upgrade/upgrade_csv_block.yaml.txt
Labels: size/XS

#196 Create an install plan with automatic approval
  make/test.mk
  test/upgrade/devconsole_v1alpha1_upgrade_crd.yaml
  test/upgrade/installplan.yaml
Labels: size/S

#197 Change group for InstallPlan
  test/upgrade/installplan.yaml
Labels: size/XS

#198 Fix CRD name typo & disable installplan
  hack/check-crds-upgrade.sh
  make/test.mk
Labels: size/XS

#199 Replace image path
  Makefile
Labels: size/XS

#181 Test operator source
  make/test.mk
  test/operatorsource/basic_test.go
  test/operatorsource/catalogsourceconfig.yaml
  test/operatorsource/operatorsource.yaml
  test/operatorsource/subscription.yaml
Labels: approved, ok-to-test, size/L

#194 Print DevConsole operator version
  cmd/manager/main.go
  version/version.go
Labels: approved, size/XS

#201 Add CSV version to replace
  test/upgrade/upgrade.py
Labels: size/XS

#202 Delete old catalog source before creating new one
  make/test.mk
Labels: size/XS

#203 Add deploymentconfig label to all secondary resources created by component controller
  pkg/controller/component/component_controller_test.go
  pkg/resource/label.go
Labels: approved, size/S

#208 Add missing entry point to start the operator
  Dockerfile.dev
Labels: lgtm, size/XS

#210 Add chromedriver to the tools images
  Dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, ok-to-test, size/XS

#212 Add missing chromium package to the tools images.
  Dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, ok-to-test, size/XS

#205 Switch to the install_devconsole directory
  .gitignore
  hack/install_devconsole/consoledeveloper.sh
Labels: approved, ok-to-test, size/XS

#211 Add a note about YUM deps and pull request order
  openshift-ci/README.md
Labels: approved, size/XS

#215 Install htpasswd to the tools images for CI
  Dockerfile
  openshift-ci/Dockerfile.tools
Labels: approved, ok-to-test, size/XS

#209 Adds instructions to use script to see the developer perspective in…
  README.md
Labels: approved, ok-to-test, size/L

#214 replace the hard sleep
  make/test.mk
Labels: approved, size/XS
