Repository redhat-developer/devconsole-operator, pull requests merged in 2019-03, with the labels that each got.

#39 updated .gitignore with gitignore.io snippet
  .gitignore
Labels: enhancement

#50 fixing label issue
  make/test.mk
Labels: approved

#48 Check for the sanity of CRD files
  deploy/crds/devopsconsole_v1alpha1_gitsource_crd.yaml
  manifests/devopsconsole/0.1.0/devopsconsole_v1alpha1_gitsource_crd.yaml
  test/sanitychecks/crd_test.go
Labels: approved

#51 Fix use of UUID issue
  make/test.mk
Labels: approved

#53 Pass image & version as arguments
  test/olm/Dockerfile.registry
Labels: approved

#52 Test all the text file ends with a newline at EOF
  Dockerfile.dev
  cico_run_coverage.sh
  cico_run_tests.sh
  cico_setup.sh
  examples/devopsconsole_v1alpha1_component_cr.yaml
  test/sanitychecks/newline_at_eof_test.go
Labels: approved

#44 add deployment config creation in component S2I flow
  Makefile
  README.md
  deploy/role.yaml
  examples/devopsconsole_v1alpha1_component_cr.yaml
  manifests/devopsconsole/0.1.0/devopsconsole-operator.v0.1.0.clusterserviceversion.yaml
  pkg/apis/devopsconsole/v1alpha1/component_types.go
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_controller_test.go
  pkg/controller/component/component_resources.go
  pkg/resource/label.go
Labels: approved

#57 Update documentation with Dockerfile arguments
  test/README.md
Labels: approved

#47 Cleanup Makefile and Dockerfile
  .dockerignore
  .yamllint
  Dockerfile
  Dockerfile.builder
  Dockerfile.deploy
  Dockerfile.deploy.rhel
  Makefile
  cico_build_deploy.sh
  cico_run_coverage.sh
  cico_run_tests.sh
  cico_setup.sh
  cmd/manager/main.go
  gofmt_exclude
  make/deploy.mk
  make/dev.mk
  make/docker.mk
  make/find-tools.mk
  make/format.mk
  make/git.mk
  make/go.mk
  make/gofmt_exclude
  make/help.mk
  make/lint.mk
  make/out.mk
  make/test.mk
  make/verbose.mk
  manifests/devopsconsole/devopsconsole.package.yaml
  test/sanitychecks/newline_at_eof_test.go
Labels: approved, lgtm

#59 Create image inside which build and test runs
  openshift-ci/Dockerfile.tools
Labels: approved

#60 Add git committer info to image/container
  openshift-ci/Dockerfile.tools
Labels: approved

#61 rename to dev console
  Dockerfile
  README.md
  build/Dockerfile
  cico_setup.sh
  cmd/manager/main.go
  deploy/crds/devconsole_v1alpha1_component_crd.yaml
  deploy/crds/devconsole_v1alpha1_gitsource_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  deploy/test/operator_test.yaml
  deploy/test/role_binding_test.yaml
  examples/devopsconsole_v1alpha1_component_cr.yaml
  examples/devopsconsole_v1alpha1_gitsource_cr.yaml
  make/deploy.mk
  make/dev.mk
  make/docker.mk
  make/test.mk
  manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml
  manifests/devconsole/0.1.0/devconsole_v1alpha1_component_crd.yaml
  manifests/devconsole/0.1.0/devconsole_v1alpha1_gitsource_crd.yaml
  manifests/devconsole/devconsole.package.yaml
  manifests/devopsconsole/devopsconsole.package.yaml
  openshift-ci/Dockerfile.tools
  pkg/apis/addtoscheme_components_v1alpha1.go
  pkg/apis/addtoscheme_devopsconsole_v1alpha1.go
  pkg/apis/devconsole-operator/v1alpha1/doc.go
  pkg/apis/devconsole-operator/v1alpha1/gitsource_types.go
  pkg/apis/devconsole-operator/v1alpha1/register.go
  pkg/apis/devconsole-operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devconsole-operator/v1alpha1/zz_generated.defaults.go
  pkg/apis/devconsole-operator/v1alpha1/zz_generated.openapi.go
  pkg/apis/devconsole/v1alpha1/component_types.go
  pkg/apis/devconsole/v1alpha1/doc.go
  pkg/apis/devconsole/v1alpha1/register.go
  pkg/apis/devconsole/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devconsole/v1alpha1/zz_generated.defaults.go
  pkg/apis/devconsole/v1alpha1/zz_generated.openapi.go
  pkg/apis/devopsconsole-operator/v1alpha1/doc.go
  pkg/apis/devopsconsole/v1alpha1/doc.go
  pkg/controller/add_component.go
  pkg/controller/component/component_controller.go
  pkg/controller/component/component_controller_test.go
  pkg/controller/component/component_resources.go
  test/README.md
  test/e2e/component_operator_test.go
  test/olm/Dockerfile.registry
  test/sanitychecks/crd_test.go
Labels: approved
